// Generated by CoffeeScript 1.3.3
(function() {
  var enable_autocomplete, enable_select_handler;

  jQuery(function() {
    return $('#add_criterion_link').click(function() {
      var filter, str, _i, _len, _ref;
      str = "<div id='select_filter' class='select inline'>      <select id='criterions_" + gon.criterion_count + "_filter_id'               name='criterions[" + gon.criterion_count + "][filter_id]'               criterionnum=\"" + gon.criterion_count + "\"              class=\"criterions_filter_select\">";
      _ref = gon.filters;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        filter = _ref[_i];
        str += "<option value='" + filter.id + "'>" + filter.name + "</option>";
      }
      str += "</select>";
      str += "</div>";
      str += "<div id='autocomplete_criterion', class='inline'>";
      str += "<input data-autocomplete-source=\"/autocomplete_criterion/1.json\"               id=\"criterions_" + gon.criterion_count + "_name\"               name=\"criterions[" + gon.criterion_count + "][name]\"               type=\"text\"              class=\"criterions_name_field\">";
      str += "</div>";
      str += "<br>";
      $('#add_criterions').append(str);
      gon.criterion_count++;
      enable_select_handler();
      enable_autocomplete();
      return false;
    });
  });

  enable_select_handler = function() {
    return $('select.criterions_filter_select').change(function() {
      var criterion_num, filter_id;
      criterion_num = $(this).attr('criterionnum');
      filter_id = $(this).find('option:selected').attr("value");
      $("#criterions_" + criterion_num + "_name").attr('data-autocomplete-source', "/autocomplete_criterion/" + filter_id + ".json");
      return enable_autocomplete();
    });
  };

  enable_autocomplete = function() {
    return $('input.criterions_name_field').each(function() {
      return $(this).autocomplete({
        source: $(this).attr('data-autocomplete-source')
      });
    });
  };

  jQuery(function() {
    var extractLast, split;
    split = function(val) {
      return val.split(/,\s*/);
    };
    extractLast = function(term) {
      return split(term).pop();
    };
    return $("#ololo").bind("keydown", function(event) {
      if (event.keyCode === $.ui.keyCode.TAB && $(this).data("autocomplete").menu.active) {
        return event.preventDefault();
      }
    }).autocomplete({
      source: function(request, response) {
        return $.getJSON("search.php", {
          term: extractLast(request.term)
        }, response);
      },
      search: function() {
        var term;
        term = extractLast(this.value);
        if (term.length < 1) {
          return false;
        }
      },
      focus: function() {
        return false;
      },
      select: function(event, ui) {
        var terms;
        terms = split(this.value);
        terms.pop();
        terms.push(ui.item.value);
        terms.push("");
        this.value = terms.join(", ");
        return false;
      },
      create: function() {
        return $(this).autocomplete("search", '');
      },
      close: function() {
        return $(this).autocomplete("search", '');
      }
    });
  });

}).call(this);
